spring:
  datasource:
    url: jdbc:postgresql://${USER_SERVICE_DB_HOST:localhost}:${USER_SERVICE_DB_PORT:5432}/${USER_SERVICE_DB_NAME:rione-users}
    username: ${USER_SERVICE_DB_USERNAME:rione_user}
    password: ${USER_SERVICE_DB_PASSWORD:rione_password}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
