package com.rione.post.domain.event;

public enum PostEventType {

	POST_CREATED,
	POST_CONTENT_UPDATED,
	POST_DELETED,
	COMMENT_ADDED,
	COMMENT_UPDATED,
	COMMENT_REMOVED,
	REACTION_ADDED,
	REACTION_UPDATED,
	REACTION_REMOVED
}
