server:
  port: ${API_GATEWAY_PORT:8080}

rione:
  gateway:
    routes:
      user-service-uri: ${RIONE_GATEWAY_ROUTES_USER_SERVICE_URI:http://localhost:8081}
      social-service-uri: ${RIONE_GATEWAY_ROUTES_SOCIAL_SERVICE_URI:http://localhost:8082}
      notification-service-uri: ${RIONE_GATEWAY_ROUTES_NOTIFICATION_SERVICE_URI:http://localhost:8084}
      post-service-uri: ${RIONE_GATEWAY_ROUTES_POST_SERVICE_URI:http://localhost:8083}

management:
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: api-gateway
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,circuitbreakers,circuitbreakerevents

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      user-service:
        base-config: default
      social-service:
        base-config: default
      notification-service:
        base-config: default
      post-service:
        base-config: default

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: user-service
        url: /users/v3/api-docs
      - name: social-service
        url: /social/v3/api-docs
      - name: notification-service
        url: /notifications/v3/api-docs
      - name: post-service
        url: /posts/v3/api-docs
