server:
  port: ${API_GATEWAY_PORT:8080}

rione:
  gateway:
    routes:
      user-service-uri: ${RIONE_GATEWAY_ROUTES_USER_SERVICE_URI:http://localhost:8081}
      social-service-uri: ${RIONE_GATEWAY_ROUTES_SOCIAL_SERVICE_URI:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: user-service
        url: /users/v3/api-docs
      - name: social-service
        url: /social/v3/api-docs
