export const neighborhoods = [
  { id: 1, name: "Saragozza", city: "Bologna" },
  { id: 2, name: "Navile", city: "Bologna" },
];

export const demoPeople = [
  {
    id: 1,
    name: "Luigi",
    surname: "Verdi",
    username: "luigino",
    mail: "luigi@example.com",
    neighborhoodId: 1,
    bio: "I help neighbors with local errands and daily coordination.",
  },
  {
    id: 2,
    name: "Admin",
    surname: "Rione",
    username: "admin",
    mail: "admin@rione.test",
    neighborhoodId: 1,
    bio: "Local administrator for Rione testing.",
  },
  {
    id: 3,
    name: "Sara",
    surname: "One",
    username: "saragozza.one",
    mail: "saragozza.one@rione.test",
    neighborhoodId: 1,
    bio: "Seed user living in Saragozza for local tests.",
  },
  {
    id: 4,
    name: "Sergio",
    surname: "Two",
    username: "saragozza.two",
    mail: "saragozza.two@rione.test",
    neighborhoodId: 1,
    bio: "Second seed user living in Saragozza for tests.",
  },
  {
    id: 5,
    name: "Nadia",
    surname: "One",
    username: "navile.one",
    mail: "navile.one@rione.test",
    neighborhoodId: 2,
    bio: "Seed user living in Navile for local tests.",
  },
  {
    id: 6,
    name: "Nico",
    surname: "Two",
    username: "navile.two",
    mail: "navile.two@rione.test",
    neighborhoodId: 2,
    bio: "Second seed user living in Navile for local tests.",
  },
  {
    id: 7,
    name: "Anna",
    surname: "Bianchi",
    username: "anna.bianchi",
    mail: "anna.bianchi@rione.test",
    neighborhoodId: 1,
    bio: "I organize evening walks and reading circles for the block.",
  },
  {
    id: 8,
    name: "Marco",
    surname: "Conti",
    username: "marco.conti",
    mail: "marco.conti@rione.test",
    neighborhoodId: 1,
    bio: "I keep the courtyard tools in order and help with small repairs.",
  },
  {
    id: 9,
    name: "Giulia",
    surname: "Rinaldi",
    username: "giulia.rinaldi",
    mail: "giulia.rinaldi@rione.test",
    neighborhoodId: 2,
    bio: "I coordinate neighborhood dinners and shared garden updates.",
  },
  {
    id: 10,
    name: "Paolo",
    surname: "Moretti",
    username: "paolo.moretti",
    mail: "paolo.moretti@rione.test",
    neighborhoodId: 2,
    bio: "I help neighbors with bikes, errands, and local message boards.",
  },
];
